AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test

Globals:
  Function:
    Timeout: 3

Resources:
  # Función GetTestRequests
  GetTestRequests:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: GetTestRequests.getTestRequests
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /solicitud-test
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - GetTestRequests.ts

  # Función GetRequestByRadicate
  GetRequestByRadicate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: GetRequestsRadicate.getRequestByRadicate
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /solicitud-test/{radicado}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - GetRequestsRadicate.ts

  # Función GetRequestsByDate
  GetRequestsByDate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: GetRequestsByDate.getRequestsByDate
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /solicitudes
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - GetRequestsByDate.ts

Outputs:
  # Para GetTestRequests
  GetTestRequestsApi:
    Description: "API Gateway endpoint URL for Prod stage for GetTestRequests function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/solicitud-test/"
  GetTestRequestsArn:
    Description: "GetTestRequests Lambda Function ARN"
    Value: !GetAtt GetTestRequests.Arn

  # Para GetRequestByRadicate
  GetRequestByRadicateApi:
    Description: "API Gateway endpoint URL for Prod stage for GetRequestByRadicate function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/solicitud-test/{radicado}"
  GetRequestByRadicateArn:
    Description: "GetRequestByRadicate Lambda Function ARN"
    Value: !GetAtt GetRequestByRadicate.Arn

  # Para GetRequestsByDate
  GetRequestsByDateApi:
    Description: "API Gateway endpoint URL for Prod stage for GetRequestsByDate function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/solicitudes"
  GetRequestsByDateArn:
    Description: "GetRequestsByDate Lambda Function ARN"
    Value: !GetAtt GetRequestsByDate.Arn
